[project]
name = "crewai_chatbot"
version = "0.1.0"
description = "crewai-chatbot using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<=3.13"
dependencies = [
    "crewai[tools]>=0.76.9,<1.0.0"
]

[project.scripts]
crewai_chatbot = "crewai_chatbot.main:run"
run_crew = "crewai_chatbot.main:run"
train = "crewai_chatbot.main:train"
replay = "crewai_chatbot.main:replay"
test = "crewai_chatbot.main:test"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
